services:
  marketing_pg:
    container_name: marketing_pg
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - '5437:5432'

  marketing_redis:
    container_name: marketing_redis
    image: redis:alpine
    env_file:
      - docker.env
    ports:
      - '6380:6379'